[package]
name = "rs-library"
version = "0.0.0"
edition = "2021"

[dependencies]
actix-web = "*"
bcrypt = "*"
regex = "*"
rand = "*"
rusqlite = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
